version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootLinkedin123
      MYSQL_DATABASE: prodUser
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootuser
    ports:
      - "3306:3306"
    networks:
      - your_network_name  
networks:
  your_network_name:
    external: true
